services:
  regtest:
    image: "doichain/core:dc0.20.1.15"
    container_name: regtest
    ports:
      - "18332:18332"
      - "18443:18443"
      - "18445:18445"
    # command: ["/usr/local/bin/doichaind"]
    volumes:
      - ./docker/doichain-regtest.conf:/home/doichain/.doichain/doichain.conf

  electrumx:
    container_name: electrumx
    hostname: electrumx
    image: "doichain/electrumx:dc1.2.1"
    depends_on:
      - regtest
    volumes:
      # - ./db:/var/lib/electrumx
      - ./docker/startElectrumDOIRegTest.sh:/startElectrumDOIRegTest.sh
    entrypoint: ["/startElectrumDOIRegTest.sh"]
    ports:
      - "50001:50001"
      - "50002:50002"
      - "8443:8443" 
    stdin_open: true
    tty: true
    privileged: true

  relay-service:
    image: "silkroadnomad/libp2p-relay-relay-service:v0.12.32"
    ports:
      - "8080:8080"
      - "1235:1235"
      - "9091:9091"
      - "9090:9090"
      - "12345:12345"
      - "3000:3000"
    depends_on:
      - electrumx
    entrypoint: ["/usr/src/app/entrypoint.sh", "generate-key"]
    command: ["node", "--max-old-space-size=8192", "relay/src/start-relay.js"]

volumes:
  doichain-data: